### ISSUE TITLE
How can I test SYSU

### ISSUE THREAD

**Issue by th0214** [wanggrun/triplet#6]
Hi, I have a new question.
I want to test sysu.
Which config file should I use to test it?

**Comment by wanggrun** [comment]
Dear @th0214 , Thank you again for your interest in our work. You can refer to the code here for testing on SYSU-30k:
https://github.com/wanggrun/SYSU-30k/tree/master/Using_SYSU30k_Test_Set

What you need to do is to write a new model.py. According to the results of our latest run, the accuracy will be higher than the results we reported in our paper.

Best regards,

**Comment by th0214** [comment]
Thank you for your reply.
Currently, I train with a triplet and get a checkpoint, and I hope to test it using this checkpoint.
If you look at the model composition written in the config, it is divided into backbone, neck, and head, so can you tell me if there is a way to bring only the model part? 
Or can you upload the model you used to get the result value written in the paper?

**Comment by wanggrun** [comment]
Dear @th0214 , you can run the following script to extract the backbone weights.

python tools/extract_backbone_weights.py  xxxxxxxxx/sysu30k_ep10.pth    xxxxxx/sysu30k_backbone_ep10.pth

Best regards,

**Comment by wanggrun** [comment]
Dear @th0214 , thanks for your interest in our work. The training and testing codes for SYSU-30k have been available.

Please see:
https://github.com/wanggrun/SYSU-30k/tree/master/Self-Supervised-ReID

Best regards,
